# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_yBFCQzVykaz-B7y0qzQcnaC9582_f5
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/graphdeco-inria/gaussian-splatting --recursive
# %cd gaussian-splatting

!pip install plyfile tqdm opencv-python joblib
!pip install submodules/diff-gaussian-rasterization
!pip install submodules/simple-knn
!pip install submodules/fused-ssim

!apt-get install -y colmap

!mkdir -p /content/my_dataset/images
!mkdir -p /content/my_dataset/sparse/0

from google.colab import drive
drive.mount('/content/drive')

!cp -r /content/drive/MyDrive/3DGSdataset/input/* /content/my_dataset/images

!cp /content/drive/MyDrive/3DGSdataset/cameras.bin /content/my_dataset/sparse/0/
!cp /content/drive/MyDrive/3DGSdataset/images.bin /content/my_dataset/sparse/0/
!cp /content/drive/MyDrive/3DGSdataset/points3D.bin /content/my_dataset/sparse/0/

import os
os.environ['PYTORCH_ALLOC_CONF'] = 'expandable_segments:True'

!python train.py \
    -s /content/my_dataset \
    -m /content/output \
    --iterations 30000 \
    --resolution 4 \
    --densify_grad_threshold 0.0003 \
    --densification_interval 200 \
    --densify_until_iter 12000 \
    --save_iterations 7000 15000 30000 \
    --checkpoint_iterations 7000 15000 30000

!cp -r /content/output /content/drive/MyDrive/gaussian_splatting_output
print("Saved to Drive!")

import numpy as np
from plyfile import PlyData

plydata = PlyData.read('/content/drive/MyDrive/gaussian_splatting_output/point_cloud/iteration_30000/point_cloud.ply')
vertex = plydata['vertex']

scale_0 = np.exp(vertex['scale_0'])
scale_1 = np.exp(vertex['scale_1'])
scale_2 = np.exp(vertex['scale_2'])

scales = np.stack([scale_0, scale_1, scale_2], axis=1)

# ---- ANISOTROPY ANALYSIS ----

max_scale = scales.max(axis=1)
min_scale = scales.min(axis=1) + 1e-10
anisotropy_ratio = max_scale / min_scale

global_median_scale = np.median(scales)

print("=" * 50)
print("GAUSSIAN SCALE STATISTICS")
print("=" * 50)
print(f"Total Gaussians:         {len(scales)}")

print(f"\nMean scales:             sx={scale_0.mean():.5f}, sy={scale_1.mean():.5f}, sz={scale_2.mean():.5f}")
print(f"Std scales:              sx={scale_0.std():.5f},  sy={scale_1.std():.5f},  sz={scale_2.std():.5f}")

print(f"\nANISOTROPY RATIO (max_scale / min_scale):")
print(f"  Mean:                  {anisotropy_ratio.mean():.2f}")
print(f"  Median:                {np.median(anisotropy_ratio):.2f}")
print(f"  Max:                   {anisotropy_ratio.max():.2f}")

print(f"  >2x anisotropic:       {(anisotropy_ratio > 2).sum()} ({100 * (anisotropy_ratio > 2).mean():.1f}%)")
print(f"  >5x anisotropic:       {(anisotropy_ratio > 5).sum()} ({100 * (anisotropy_ratio > 5).mean():.1f}%)")
print(f"  >10x anisotropic:      {(anisotropy_ratio > 10).sum()} ({100 * (anisotropy_ratio > 10).mean():.1f}%)")

print(f"\nROBUST ANISOTROPY:")
print(f"  95th percentile:       {np.percentile(anisotropy_ratio, 95):.2f}")
print(f"  99th percentile:       {np.percentile(anisotropy_ratio, 99):.2f}")

flat = ((anisotropy_ratio > 3) & (min_scale < global_median_scale)).sum()
needle = ((anisotropy_ratio > 3) & (min_scale >= global_median_scale)).sum()
sphere = (anisotropy_ratio <= 2).sum()

print(f"\nSHAPE CLASSIFICATION:")
print(f"  Near-spherical (r<=2): {sphere} ({100 * sphere / len(scales):.1f}%)")
print(f"  Flat/disc-like (r>3):  {flat} ({100 * flat / len(scales):.1f}%)")
print(f"  Needle/elongated:      {needle} ({100 * needle / len(scales):.1f}%)")

print("=" * 50)

import matplotlib.pyplot as plt
import numpy as np

anisotropy_clipped = np.clip(anisotropy_ratio, 0, 50)

sample_size = min(5000, len(scales))
sample = np.random.choice(len(scales), sample_size, replace=False)

global_max = np.percentile(scales, 99)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].hist(anisotropy_clipped, bins=100, color='steelblue', edgecolor='none')
axes[0].set_xlabel('Anisotropy Ratio (max/min scale)')
axes[0].set_ylabel('Number of Gaussians')
axes[0].set_title('Anisotropy Ratio Distribution')
axes[0].axvline(x=2, color='red', linestyle='--', label='Near-spherical threshold (r=2)')
axes[0].axvline(x=5, color='orange', linestyle='--', label='Strong anisotropy (r=5)')
axes[0].legend()

axes[1].hist(scale_0, bins=100, alpha=0.5, label='scale_x', color='red')
axes[1].hist(scale_1, bins=100, alpha=0.5, label='scale_y', color='green')
axes[1].hist(scale_2, bins=100, alpha=0.5, label='scale_z', color='blue')

axes[1].set_xlabel('Scale Value')
axes[1].set_ylabel('Count')
axes[1].set_title('Per-Axis Gaussian Scale Distribution')
axes[1].legend()

axes[1].set_xlim(0, np.percentile(scales, 99))

min_sample = scales[sample].min(axis=1)
max_sample = scales[sample].max(axis=1)

axes[2].scatter(min_sample, max_sample, alpha=0.15, s=2, color='purple')
axes[2].set_xlabel('Min Scale (smallest axis)')
axes[2].set_ylabel('Max Scale (largest axis)')
axes[2].set_title('Gaussian Shape Anisotropy')

axes[2].plot([0, global_max], [0, global_max], 'r--', label='Isotropic line (x=y)')
axes[2].set_xlim(0, global_max)
axes[2].set_ylim(0, global_max)
axes[2].legend()

plt.tight_layout()

save_path = '/content/drive/MyDrive/anisotropy_analysis.png'
plt.savefig(save_path, dpi=300, bbox_inches='tight')

plt.show()

print(f"Plot saved to: {save_path}")